game-time: 240
lobby-time: 60
locale: enUS
Arena-Spectate: true
Nametag-Visible: true
Debug: false
Stats:
  Track: false
Gameplay:
  Spawn-Time: 3
In-Game:
  Kills: "Kills"
  Killed: "killed"
Economy:
  Reward-Team: 100
