author: Borgdude
description: "Simple Paintball"
main: com.borgdude.paintball.Main
name: Simple_PaintBall
version: "0.1.2"

commands:
  gun:
    description: Gives paintball gun
    usage: /<command>
  pb:
    description: Commands
    usage: /<command> <option>

permissions:
  paintball.admin:
    default: op
    description: admin commands