author: Borgdude
description: "Simple Paintball"
main: com.borgdude.paintball.Main
name: Simple_PaintBall
version: "0.2.5"
api-version: 1.13
softdepend: [Vault]

commands:
  gun:
    description: Gives paintball gun
    usage: /<command>
  pb:
    description: Commands
    usage: /<command> <options> | /pb help - more info

permissions:
  paintball.admin:
    default: op
    description: admin commands